# Generated by Django 2.2.7 on 2020-09-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_auto_20200920_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='member',
            new_name='activity_periods',
        ),
    ]
